# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Banner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Banner - a model defined in OpenAPI

        id: The id of this Banner [Optional].
        image_url: The image_url of this Banner [Optional].
    """

    id: Optional[str] = Field(alias="id", default=None)
    image_url: Optional[str] = Field(alias="imageURL", default=None)

Banner.update_forward_refs()
