# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Product(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Product - a model defined in OpenAPI

        id: The id of this Product [Optional].
        name: The name of this Product [Optional].
        description: The description of this Product [Optional].
        category_id: The category_id of this Product [Optional].
        price: The price of this Product [Optional].
        image_url: The image_url of this Product [Optional].
    """

    id: Optional[str] = Field(alias="id", default=None)
    name: Optional[str] = Field(alias="name", default=None)
    description: Optional[str] = Field(alias="description", default=None)
    category_id: Optional[str] = Field(alias="categoryId", default=None)
    price: Optional[str] = Field(alias="price", default=None)
    image_url: Optional[str] = Field(alias="imageURL", default=None)

Product.update_forward_refs()
