# This is a basic workflow to help you get started with Actions

name: Push To Yandex Cloud CR

# Controls when the action will run. 
on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BACKEND_IMAGE: funnypuny-backend:${{ github.sha }}
  NGINX_IMAGE: funnypuny-nginx:${{ github.sha }}
  
  CR_REGISTRY: crp5q0eep54cgj8ppn6e
  CR_REPOSITORY: funnypuny-cr-repo

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Login to Yandex Cloud Container Registry
      id: login-cr
      uses: yc-actions/yc-cr-login@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

    - name: Build, tag, and push image to Yandex Cloud Container Registry
      run: |
        docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$BACKEND_IMAGE ./app
        docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$BACKEND_IMAGE

  build-nginx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Login to Yandex Cloud Container Registry
      id: login-cr
      uses: yc-actions/yc-cr-login@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

    - name: Build, tag, and push image to Yandex Cloud Container Registry
      run: |
        docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$NGINX_IMAGE ./nginx
        docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$NGINX_IMAGE
