name: Tests
on:
  push:
    branches: [ develop ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@develop
      with:
        python-version: '3.5'
    - name: Docker compose build
      run: docker-compose build 
    - name: Docker compose up -d
      run: docker-compose up -d
    - name: To folder
      run: cd app/tests
    - name: Start tests
      run: python test_get_ping_api.py
    
