# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from src.models.base_model_ import Model
from src import util


class GetPingResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status: str=None):
        """GetPingResponse - a model defined in OpenAPI

        :param status: The status of this GetPingResponse.
        """
        self.openapi_types = {
            'status': str
        }

        self.attribute_map = {
            'status': 'status'
        }

        self._status = status

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GetPingResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GetPingResponse of this GetPingResponse.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self):
        """Gets the status of this GetPingResponse.

        server status

        :return: The status of this GetPingResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this GetPingResponse.

        server status

        :param status: The status of this GetPingResponse.
        :type status: str
        """
        allowed_values = ["ok"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
